name: express-server-filebeat
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/*.log
    fields:
      service: express-server
      test: 123
      app: express-app
      username: ${ELASTICSEARCH_USERNAME}
      log_type: "express-server"
    fields_under_root: true
    json:
      keys_under_root: true
      overwrite_keys: true
      message_key: "message"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "express-server"
